package com.pathaks.employeesoap.employeews;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-07T20:31:43.382+05:30
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://employeesoap.pathaks.com/employeeWS/", name = "employeeWS")
@XmlSeeAlso({com.pathaks.employeesoap.employeeschema.ObjectFactory.class, ObjectFactory.class})
public interface EmployeeWS {

    @WebMethod(operationName = "UpdateEmployee", action = "http://employeesoap.pathaks.com/employeeWS/UpdateEmployee")
    @RequestWrapper(localName = "UpdateEmployee", targetNamespace = "http://employeesoap.pathaks.com/employeeWS/", className = "com.pathaks.employeesoap.employeews.UpdateEmployee")
    @ResponseWrapper(localName = "UpdateEmployeeResponse", targetNamespace = "http://employeesoap.pathaks.com/employeeWS/", className = "com.pathaks.employeesoap.employeews.UpdateEmployeeResponse")
    @WebResult(name = "UpdateEmployeeResponse", targetNamespace = "")
    public com.pathaks.employeesoap.employeeschema.Employee updateEmployee(

        @WebParam(name = "UpdateEmployeeRequest", targetNamespace = "")
        com.pathaks.employeesoap.employeeschema.Employee updateEmployeeRequest
    );

    @WebMethod(operationName = "DeleteEmployee", action = "http://employeesoap.pathaks.com/employeeWS/DeleteEmployee")
    @RequestWrapper(localName = "DeleteEmployee", targetNamespace = "http://employeesoap.pathaks.com/employeeWS/", className = "com.pathaks.employeesoap.employeews.DeleteEmployee")
    @ResponseWrapper(localName = "DeleteEmployeeResponse", targetNamespace = "http://employeesoap.pathaks.com/employeeWS/", className = "com.pathaks.employeesoap.employeews.DeleteEmployeeResponse")
    @WebResult(name = "ResponseMessage", targetNamespace = "")
    public java.lang.String deleteEmployee(

        @WebParam(name = "empID", targetNamespace = "")
        int empID
    );

    @WebMethod(operationName = "GetEmployee", action = "http://employeesoap.pathaks.com/employeeWS/GetEmployee")
    @RequestWrapper(localName = "GetEmployee", targetNamespace = "http://employeesoap.pathaks.com/employeeWS/", className = "com.pathaks.employeesoap.employeews.GetEmployee")
    @ResponseWrapper(localName = "GetEmployeeResponse", targetNamespace = "http://employeesoap.pathaks.com/employeeWS/", className = "com.pathaks.employeesoap.employeews.GetEmployeeResponse")
    @WebResult(name = "GetEmployeeResponse", targetNamespace = "")
    public com.pathaks.employeesoap.employeeschema.Employee getEmployee(

        @WebParam(name = "empID", targetNamespace = "")
        int empID
    );

    @WebMethod(operationName = "GetAllEmployees", action = "http://employeesoap.pathaks.com/employeeWS/GetAllEmployees")
    @RequestWrapper(localName = "GetAllEmployees", targetNamespace = "http://employeesoap.pathaks.com/employeeWS/", className = "com.pathaks.employeesoap.employeews.GetAllEmployees")
    @ResponseWrapper(localName = "GetAllEmployeesResponse", targetNamespace = "http://employeesoap.pathaks.com/employeeWS/", className = "com.pathaks.employeesoap.employeews.GetAllEmployeesResponse")
    @WebResult(name = "GetEmployeesResponse", targetNamespace = "")
    public com.pathaks.employeesoap.employeeschema.Employees getAllEmployees()
;

    @WebMethod(operationName = "AddEmployee", action = "http://employeesoap.pathaks.com/employeeWS/AddEmployee")
    @RequestWrapper(localName = "AddEmployee", targetNamespace = "http://employeesoap.pathaks.com/employeeWS/", className = "com.pathaks.employeesoap.employeews.AddEmployee")
    @ResponseWrapper(localName = "AddEmployeeResponse", targetNamespace = "http://employeesoap.pathaks.com/employeeWS/", className = "com.pathaks.employeesoap.employeews.AddEmployeeResponse")
    @WebResult(name = "AddEmployeeResponse", targetNamespace = "")
    public com.pathaks.employeesoap.employeeschema.Employee addEmployee(

        @WebParam(name = "AddRequest", targetNamespace = "")
        com.pathaks.employeesoap.employeeschema.Employee addRequest
    );
}
