package com.pathaks.employeesoap.employeews;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-07T20:31:43.566+05:30
 * Generated source version: 3.3.6
 *
 */
@WebServiceClient(name = "employeeWS",
                  wsdlLocation = "file:/E:/spathak/vscode/employee-soap/src/main/resources/EmployeeService.wsdl",
                  targetNamespace = "http://employeesoap.pathaks.com/employeeWS/")
public class EmployeeWS_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://employeesoap.pathaks.com/employeeWS/", "employeeWS");
    public final static QName EmployeeWSSOAP = new QName("http://employeesoap.pathaks.com/employeeWS/", "employeeWSSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/spathak/vscode/employee-soap/src/main/resources/EmployeeService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EmployeeWS_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/E:/spathak/vscode/employee-soap/src/main/resources/EmployeeService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EmployeeWS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EmployeeWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeWS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EmployeeWS_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EmployeeWS_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EmployeeWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EmployeeWS
     */
    @WebEndpoint(name = "employeeWSSOAP")
    public EmployeeWS getEmployeeWSSOAP() {
        return super.getPort(EmployeeWSSOAP, EmployeeWS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeWS
     */
    @WebEndpoint(name = "employeeWSSOAP")
    public EmployeeWS getEmployeeWSSOAP(WebServiceFeature... features) {
        return super.getPort(EmployeeWSSOAP, EmployeeWS.class, features);
    }

}
